### ISSUE TITLE
Keysanity: Ice Beam Missile seems to be missing key requirement

### ISSUE THREAD

**Issue by TarThoron** [tewtal/SMZ3Randomizer#105]
https://alpha.samus.link/seed/K8DBdylzTFibT1mkQebfkg has ToH big key there, and ToH is a crystal, but UN1 is in Ganon's tower.

https://alpha.samus.link/seed/tiRKNkl_RvKaEqPBkURnmw has the second Castle Tower key there, and all other logical DW access is locked in DW. UN1 is again in GT.

**Comment by RebelusQuo** [comment]
Actually, having each issue separate would be better. It makes it easier to craft atomic commits and pair them with the corresponding issue.

**Comment by TarThoron** [comment]
Sure. This is a step up from being scattered across various channels in both discords, plus total for sure sees this (he asked to have known issues posted here).

**Comment by tewtal** [comment]
This was missing a key requirement in Hard for the lower path going from crocomire.
