### ISSUE TITLE
Keysanity: Ocean Missiles missing morph requirement

### ISSUE THREAD

**Issue by TarThoron** [tewtal/SMZ3Randomizer#106]
At a guess, this is because removing the power bomb door removed CanUsePowerBombs, which was the only morph check from the moat side.

**Comment by tewtal** [comment]
There is already a Morph requirement for this item as can be seen her:
https://github.com/tewtal/SMZ3Randomizer/blob/68dcb656f4401e74a0a50fb28543dae62c193a7e/Randomizer.SMZ3/Regions/SuperMetroid/Crateria/East.cs#L14

**Comment by tewtal** [comment]
My bad, there is a Morph check for Normal but not Hard mode
