### ISSUE TITLE
Keysanity: Energy Requirements for Wave Beam Lower Route

### ISSUE THREAD

**Issue by TarThoron** [tewtal/SMZ3Randomizer#108]
Hellrunning to Wave from Nutella Refill cost Osse ~875 health each way. Lower skilled players are likely closer to 1000. This means at least one crystal flash would be needed.

With Varia and no grapple/space, Spiky Acid Snake room deals ~150 health with slightly less than ideal movement. Grav suit would lessen this, as you can maintain speed through the lava.

**Comment by tewtal** [comment]
I've resolved this for now by checking for either L2 Norfair Card or Varia suit. We can take a look at this later to include hell running.
