### ISSUE TITLE
Graphical glitch in potion shop

### ISSUE THREAD

**Issue by SmolBig** [tewtal/SMZ3Randomizer#124]
User "BTB" in Discord reported a graphical glitch in potion shop when buying a potion. Steve also indicated that he'd seen the glitch there and in other places. He said he suspected it was related to the temporary light cone patch. I ran through the debugger and found that the potion shop is indeed being detected as a dark room. When I replaced the first byte of EnableTemporaryCone with an RTS through the debugger it corrected the bug.

I'll try to fix this and submit a PR or an additional comment soon.

**Comment by SmolBig** [comment]
https://github.com/tewtal/alttp_sm_combo_randomizer_rom/pull/46

**Comment by tewtal** [comment]
PR Merged so this will be fixed in the next update.
