### ISSUE TITLE
Keysanity glitch with silver arrows

### ISSUE THREAD

**Issue by RecklessHarlot** [tewtal/SMZ3Randomizer#152]
Bug report: I was playing keysanity seed C2tqm51BRvym_RABPnvpIA. Silvers were acquired from Zora early on. After getting bow I noticed that regular arrows were being used. I don't know if silvers never activated or it changed at some point. I did close and reset from a save state in between. I went back to Zora and could not re-get silvers.

**Comment by tewtal** [comment]
What happened here was most likely that the silver arrow ended up being de-selected. There's a feature in the randomizer that lets you toggle between silver and regular arrows using the Y button when having the bow selected in the menu. So it's possible that you could have selected the silver arrows this way.

**Comment by RecklessHarlot** [comment]
That was it. Didn’t realize that was a thing, never came up before. Thanks
much.
