### ISSUE TITLE
Infinite Bomb Jump to Hard logic?

### ISSUE THREAD

**Issue by Vivelin** [tewtal/SMZ3Randomizer#159]
Is there any interest in moving IBJ to Hard logic, or maybe introducing a new Easy option that is like Normal but without IBJ? 

I'm only a viewer of SMZ3 streams, but watching someone get stuck and almost quit in frustration over a few tricky required IBJs isn't very fun. Apparently this is a hotly debated topic but I couldn't find anything about it here on GitHub, so I figured I'd ask before putting in any effort.

**Comment by RebelusQuo** [comment]
IBJ is considered a basic technique used as logical access for a number of locations. I don't see this changing.

There are some few places that requires starting an IBJ mid air and those I feel are a bit more questionable. While true some find mid air starts easier it does restrict the technique to only one way to start it, forcing those who learned it starting stationary on the ground to relearn.

There is an existing effort to change the logic categories, but time and planning has not allowed it to be completed yet.

**Comment by wu4** [comment]
The SM "Normal" difficulty implies you're well-informed on all of the techniques the game teaches you, including those shown in the title screen demo that appears after you've beaten the game. IBJ is one of those.

I think it would be more reasonable to include a "Beginner" difficulty that knocks IBJ (and maybe other things, to fit the beginner motif) out of logic.
