### ISSUE TITLE
Possible bug in Keysanity rando

### ISSUE THREAD

**Issue by B-u-R-n-I-n-G-f-I-r-E** [tewtal/SMZ3Randomizer#165]
Hi,

i created a game with the Keysanity option on.
But i cannot continie the game because i cannot reach a progressive item.
This is already the secound seed with similar problem.
I used the CLI randomizer fresh build from the Master.
This is my setting and seed: SLn+SLn-Se-Me-Kk-812533722 , dificulty all normal (not hard)
Below is the playthrough json for track back:
If there are open questions please feel free to ask me :-)

JSON:
[
  {
    "Eastern Palace - Compass Chest": "Hi-Jump Boots",
    "Mushroom": "Bug Catching Net",
    "Kakariko Well - Top": "Ice Rod",
    "Kakariko Well - Left": "Morphing Ball",
    "Blind's Hideout - Left": "Power Bomb",
    "Blind's Hideout - Right": "Palace of Darkness Map",
    "Bottle Merchant": "Progressive Sword",
    "Sahasrahla's Hut - Middle": "Misery Mire Map",
    "Maze Race": "Book of Mudora",
    "Aginah's Cave": "Crateria Boss Keycard",
    "Mini Moldorm Cave - Far Right": "Magic Mirror",
    "Floodgate Chest": "Castle Tower Key",
    "Sunken Treasure": "Super Missile",
    "Hyrule Castle - Map Chest": "Crateria Level 1 Keycard",
    "Link's Uncle": "Castle Tower Key",
    "Morphing Ball": "Lamp"
  },
  {
    "Desert Palace - Map Chest": "Missile",
    "Tower of Hera - Map Chest": "Grappling Beam",
    "Old Man": "Progressive Sword",
    "Sewers - Dark Cross": "Bow",
    "Missile (Crateria middle)": "Reserve Tank",
    "Missile (Crateria bottom)": "Skull Woods Key",
    "Bombs": "Palace of Darkness Key",
    "Energy Tank, Terminator": "Misery Mire Key",
    "Power Bomb (blue Brinstar)": "Moon Pearl",
    "Missile (blue Brinstar bottom)": "Magic Cape",
    "Missile (Kraid)": "Turtle Rock Key",
    "Missile (pink Brinstar top)": "Hookshot",
    "Power Bomb (red Brinstar sidehopper room)": "Wrecked Ship Level 1 Keycard",
    "Spazer": "Sewer Key"
  },
  {
    "Castle Tower - Foyer": "Gravity Suit",
    "Castle Tower - Dark Maze": "Fire Rod",
    "Palace of Darkness - Shooter Room": "Cane of Byrna",
    "Spiral Cave": "Ether",
    "Paradox Cave Upper - Right": "Progressive Shield",
    "Paradox Cave Lower - Left": "Thieves Town Map",
    "Paradox Cave Lower - Right": "Eastern Palace Big Key",
    "Sewers - Secret Room - Middle": "Wrecked Ship Boss Keycard",
    "Hyrule Castle - Boomerang Chest": "Pegasus Boots",
    "Hyrule Castle - Zelda's Cell": "Magic Powder",
    "Pyramid": "Lower Norfair Level 1 Keycard"
  },
  {
    "Eastern Palace - Big Chest": "Swamp Palace Map",
    "Lumberjack Tree": "Norfair Boss Keycard",
    "Library": "Brinstar Level 2 Keycard",  (this is the last item i was able to get)
    "Missile (outside Wrecked Ship top)": "Progressive Glove", (i can't get this item because crateria level 2 amd Maridia Level 2 doors locked)
    "Energy Tank, Mama turtle": "Palace of Darkness Big Key",
    "Missile (green Maridia tatori)": "Ganons Tower Key",
    "Missile (Wrecked Ship middle)": "Ice Palace Key",
    "Missile (Wrecked Ship top)": "Wave Beam",
    "Super Missile (Wrecked Ship left)": "Ice Palace Big Key"
  },
  {
    "Skull Woods - Map Chest": "Flute",
    "Skull Woods - Pinball Room": "Skull Woods Key",
    "Thieves' Town - Compass Chest": "Hammer",
    "South of Grove": "Energy Tank",
    "Bumper Cave": "Shovel",
    "Digging Game": "Reserve Tank",
    "Stumpy": "Skull Woods Key",
    "Hype Cave - Top": "Palace of Darkness Key",
    "Power Bomb (green Brinstar bottom)": "Maridia Level 2 Keycard"
  },
  {
    "Skull Woods - Mothula": "Progressive Glove",
    "Magic Bat": "Morph Bombs",
    "Flute Spot": "Progressive Shield"
  },
  {
    "Floating Island": "Skull Woods Big Key",
    "Checkerboard Cave": "Maridia Level 1 Keycard",
    "Hookshot Cave - Bottom Left": "Speed Booster",
    "Superbunny Cave - Bottom": "Brinstar Level 1 Keycard",
    "Hammer Pegs": "Reserve Tank",
    "Power Bomb (Crateria surface)": "Maridia Boss Keycard",
    "Missile (Crateria gauntlet left)": "Tower of Hera Map"
  },
  {
    "Skull Woods - Big Chest": "Misery Mire Key",
    "Missile (blue Brinstar middle)": "Palace of Darkness Key",
    "Super Missile (green Brinstar top)": "Reserve Tank",
    "Reserve Tank, Brinstar": "Ice Palace Map",
    "Missile (green Brinstar behind missile)": "Ganons Tower Key",
    "Energy Tank, Waterway": "Varia Suit",
    "Missile (green Maridia shinespark)": "Norfair Level 1 Keycard",
    "Missile (yellow Maridia super missile)": "Palace of Darkness Key",
    "Power Bomb (right Maridia sand pit room)": "Ganons Tower Key",
    "Reserve Tank, Wrecked Ship": "Misery Mire Key"
  },
  {
    "Palace of Darkness - Dark Basement - Right": "Turtle Rock Key",
    "Sick Kid": "Desert Palace Key",
    "Missile (lava room)": "Plasma Beam",
    "Missile (Wave Beam)": "Ganons Tower Key",
    "Energy Tank, Crocomire": "Turtle Rock Key",
    "Missile (above Crocomire)": "Ice Beam",
    "Missile (below Crocomire)": "Palace of Darkness Key",
    "Missile (Grappling Beam)": "Tower of Hera Key",
    "Missile (lower Norfair above fire flea room)": "Energy Tank",
    "Power Bomb (Power Bombs of shame)": "Palace of Darkness Key"
  },
  {
    "Palace of Darkness - Harmless Hellway": "Turtle Rock Big Key",
    "Palace of Darkness - Dark Maze - Top": "Quake",
    "Palace of Darkness - Big Chest": "Cane of Somaria",
    "Plasma Beam": "Thieves Town Big Key"
  },
  {
    "Thieves' Town - Blind's Cell": "Charge Beam",
    "Misery Mire - Main Lobby": "Misery Mire Big Key",
    "Misery Mire - Spike Chest": "Bombos",
    "Misery Mire - Big Key Chest": "Turtle Rock Key"
  },
  {
    "Misery Mire - Vitreous": "Zora's Flippers",
    "Turtle Rock - Compass Chest": "Tower of Hera Big Key",
    "Turtle Rock - Chain Chomps": "Crateria Level 2 Keycard",
    "Turtle Rock - Eye Bridge - Top Right": "Half Magic",
    "Turtle Rock - Eye Bridge - Bottom Right": "Mushroom"
  },
  {
    "Ice Palace - Compass Chest": "Bottle",
    "Ice Palace - Spike Room": "Lower Norfair Boss Keycard",
    "Ice Palace - Map Chest": "Brinstar Boss Keycard",
    "Ice Palace - Big Key Chest": "Eastern Palace Map",
    "Waterfall Fairy - Left": "Energy Tank",
    "Waterfall Fairy - Right": "Norfair Level 2 Keycard"
  },
  {
    "Energy Tank, Kraid": "Desert Palace Map",
    "Varia Suit": "Swamp Palace Key",
    "Missile (Norfair Reserve Tank)": "Thieves Town Key",
    "Missile (bubble Norfair)": "Power Bomb",
    "Missile (Speed Booster)": "Skull Woods Map"
  },
  {
    "Swamp Palace - Compass Chest": "Ice Palace Key",
    "Thieves' Town - Big Chest": "Ganons Tower Big Key",
    "Thieves' Town - Blind": "Space Jump",
    "Sahasrahla": "Desert Palace Big Key"
  },
  {
    "Desert Palace - Big Chest": "Swamp Palace Big Key",
    "Desert Palace - Lanmolas": "Progressive Shield",
    "Ganon's Tower - DMs Room - Top Left": "Energy Tank",
    "Ganon's Tower - DMs Room - Bottom Left": "Spring Ball",
    "Ganon's Tower - Compass Room - Top Right": "Energy Tank",
    "Ganon's Tower - Compass Room - Bottom Left": "Turtle Rock Map",
    "Ganon's Tower - Moldorm Chest": "Screw Attack"
  },
  {},
  {
    "Prize - Eastern Palace": "Blue/Red Pendant",
    "Prize - Desert Palace": "Red Crystal",
    "Prize - Tower of Hera": "Blue Crystal",
    "Prize - Palace of Darkness": "Blue Crystal",
    "Prize - Swamp Palace": "Blue/Red Pendant",
    "Prize - Skull Woods": "Blue Crystal",
    "Prize - Thieves' Town": "Green Pendant",
    "Prize - Ice Palace": "Blue Crystal",
    "Prize - Misery Mire": "Blue Crystal",
    "Prize - Turtle Rock": "Red Crystal",
    "Medallion Required - Misery Mire": "Quake",
    "Medallion Required - Turtle Rock": "Bombos"
  }
]

I hope this logic problen can be fixed soon.
Many thanks :-)

**Comment by tewtal** [comment]
From what I can tell I think this seed should be completable, you have access to the Wrecked Ship through Maridia by going up the  big tube (aka "the toilet") from below and then taking the long way around to access WS from behind. You don't need either Maridia Level 2 or Crateria Level 2 for that.

**Comment by B-u-R-n-I-n-G-f-I-r-E** [comment]
Oh my god, You are so right - i feel me wrong now.
I expected that the door after the short broken tube is locked.
Thank You very much.
