### ISSUE TITLE
Requirements Reversed?

### ISSUE THREAD

**Issue by bmccary** [tewtal/SMZ3Randomizer#169]
I think these requirements may be reversed.
https://github.com/tewtal/SMZ3Randomizer/blob/9600376f67713633df393745013165d3e4c6e8ad/Randomizer.SuperMetroid/Regions/Brinstar/Red.cs#L26-L32
For comparison, the requirements seem to be correct in this related file.
https://github.com/tewtal/SMZ3Randomizer/blob/9600376f67713633df393745013165d3e4c6e8ad/Randomizer.SMZ3/Regions/SuperMetroid/Brinstar/Red.cs#L23-L29

**Comment by tewtal** [comment]
Yeah this seems like a bug for sure in the SM only logic. I'll get it fixed
