### ISSUE TITLE
Can't get items in ALTTP

### ISSUE THREAD

**Issue by neptunehs** [tewtal/SMZ3Randomizer#208]
Seed:Yd4ofEnDTImKbxHzcLhzbw
Seed number:708838594
Super Metroid Logic:Normal
Goal:Defeat Ganon and Mother Brain
Open Ganon's Tower:Seven Crystals
Ganon Vulnerable:Seven Crystals
Open Tourian:Four Bosses
First Sword:Randomized
Morph Ball:Randomized
Key Shuffle:None

![2023012520494400](https://user-images.githubusercontent.com/27727785/214566372-d640c533-f89a-4519-a11c-88aecce281e1.jpg)
![2023012520494900](https://user-images.githubusercontent.com/27727785/214566373-444fd9e2-c097-44d0-aa63-2fa247b7bc73.jpg)

This is my second time face this issue
Although not in the screenshot, but magic powder that I got in brinstar is also not appear

**Comment by cassidoxa** [comment]
Press Y on the shovel/flute location and on the Mushroom/Powder location when you have both

**Comment by neptunehs** [comment]
Sorry, it's my fault for not reading the document properly
