### ISSUE TITLE
SMZ3 Multiworld - Deleting save starts Link with fighter's sword

### ISSUE THREAD

**Issue by llamasoft** [tewtal/SMZ3Randomizer#44]
Steps to reproduce:
- Go to Link to the Past, then save and quit.
- Delete the default save file, then make a new one.
- Link now has the fighter's sword.

This issue _only_ occurs on the multiworld variant of the combo randomizer.  It doesn't matter if you're doing it single-player or with other players.  The normal combo randomizer is unaffected.

**Comment by tewtal** [comment]
This is an odd one, not sure how to best fix it since deleting the ALTTP save file isn't really something that should be allowed anyway. Probably disabling the delete button completely is a good option.

**Comment by RebelusQuo** [comment]
One need to be able to restart a seed in the case of falling trap of a hard softlock, such as entering sporespawn's save station with your last PB without having bombs.

**Comment by llamasoft** [comment]
I'd be ok with removing the delete option so long as I can rename Link. 😬 

@RebelusQuo - For solo that's not too hard to fix.  For multiworld, that could be an issue.  If you delete a save after receiving an item from a different player, making a new save won't give you that item back.  You could softlock yourself even faster that way.

**Comment by tewtal** [comment]
Right, deleting the save in SM should be possible, and that should also properly wipe the ALTTP save-file so it can be re-initialized. But only deleting the ALTTP-side save file should certainly not be possible since that's initialized with some specific data. In fact, at some point the whole ALTTP file select menu will be taken out since it serves little to no purpose.

**Comment by RebelusQuo** [comment]
Aha, delete the save *in Z3*.. I misunderstood that part. yeah, should just be able to recreate the save from the SM menu.

**Comment by tewtal** [comment]
This will be fixed now in the next update thanks to this change: https://github.com/tewtal/alttp_sm_combo_randomizer_rom/pull/44
