### ISSUE TITLE
Getting to outer Maridia from portal

### ISSUE THREAD

**Issue by TarThoron** [tewtal/SMZ3Randomizer#45]
Getting to crab supers and mama turtle from the Maridia portal requires either canPassBombPassages in Aqueduct, or the ability to climb mainstreet after going through the sandpits. Sandpit route is Hard logic only, since it also requires a green gate glitch.

Also, mama turtle has a red door, and supers aren't required to get there from either Maridia or upper Norfair portals, so both items need canOpenRedDoors.

**Comment by TarThoron** [comment]
Grav+screw in Aqueduct would also work.

**Comment by TarThoron** [comment]
Stopped being lazy and wrote the changes in a PR. Hopefully didn't make any syntax errors.

**Comment by TarThoron** [comment]
Something's wrong with L37. Maybe missing a comma at the end? Fixed the missing )

**Comment by tewtal** [comment]
Thanks for this, PR #54 have been merged.
