### ISSUE TITLE
Full Spoiler

### ISSUE THREAD

**Issue by biohazardtx** [tewtal/SMZ3Randomizer#81]
Can you please bring back the full spoiler report?  I appreciate the playthrough spoiler, but I'd like to still know where all of the other non-progress items are (like the mails, magic powder, Spazer, and additional E-Tanks). I'm still learning the game and while they are non-progress items, they do make the game considerably easier and more accessible to novice players.

Thanks for putting this together!

**Comment by tewtal** [comment]
Hi, Spoiler improvements are planned and targeted for the next minor release and should be hopefully be available reasonably soon.
