### ISSUE TITLE
Registering a New Multiworld Session Destroys Registration For Previous Ones

### ISSUE THREAD

**Issue by jcbantuelle** [tewtal/SMZ3Randomizer#91]
First off, thank you so much for this randomizer and particularly the multiworld functionality!

Regarding the issue I experienced, looking through the multiworld Discord it seems to be a known issue. My understanding of the problem is that the localStorage item `clientGuid` is used for all multiworld sessions, meaning registering for a new one will overwrite the existing one.

This bit me a little while ago where a friend who has limited availability can only do shorter infrequent sessions and I unwittingly lost my registration to that game when I did a different multiworld in between.

I would be happy to implement a PR to address this, but wanted to make sure that was desirable on your end first.

My initial thought would be to do something simple like set the `sessionGuid` as the localStorage item key, and the `clientGuid` as the item value. Then the lookup could be performed by the known `sessionGuid` from the multiworld page to extract the `clientGuid` and determine if the player is a valid registrant.

The only drawback I can immediately think of would be the potential risk of localStorage eventually filling up, but given how minimal the stored content is I'm not sure that's actually concerning. If it is, the stored value could be represented as a hash with one of the values being an expiry timestamp that's checked on new registration and flushes any expired values out.

Thanks again, and if this is something you'd like for me to try tackling just let me know!

**Comment by tewtal** [comment]
Hello,

This is indeed something that's been on my mind to fix for a while now and as you mentioned it should be easy to fix in the way that you suggested. I don't see any way it would really cause any issues either apart from possibly bloating the local storage a bit which probably isn't much of an issue.

I'd be happy to accept a PR if it's something you feel you want to implement it.
