### ISSUE TITLE
Error in Moon Pearl placement

### ISSUE THREAD

**Issue by blindley** [tewtal/SMZ3Randomizer#97]
The following seed https://samus.link/seed/CJD55oGZSfSTAVFXfAlTWQ produces a rom that I cannot complete using normal play, due to inability to acquire the Moon Pearl. The playthrough claims that the Moon Pearl is located at "Missile (lower Norfair near Wave Beam)" -- I assume this refers to the item on the ledge outside the Wave Beam room, just past the one-way gate. However, that item is a 20 rupee coin, and the item at the Wave Beam location is 50 rupees. Every other item listed in the playthrough up to that point was correctly located.

**Comment by cassidoxa** [comment]
The wave beam is in Upper Norfair. The location that the spoiler is referring to is in Lower Norfair, on the way out

**Comment by RebelusQuo** [comment]
Please verify logic in the `#training-room` channel at the discord server (https://smalttplinks.page.link/discord) before opening issues as it's easy to overlook something.
